name: Trigger docs aggregation

on:
    push:
        branches: [main] # or whatever you want

jobs:
    trigger:
        runs-on: ubuntu-latest
        steps:
            - name: Call repository_dispatch
              run: |
                  curl -X POST \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer ${{ secrets.TRIGGER_DOCS_AGR }}" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    https://api.github.com/repos/modaic-ai/modaic-docs/dispatches \
                    -d '{"event_type":"run-aggregate-docs"}'
